package com.openfintechlab.jwe;

import com.openfintechlab.jwe.util.KeyGeneratorUtil;
import java.nio.charset.StandardCharsets;
import java.security.GeneralSecurityException;
import java.security.KeyFactory;
import java.security.PrivateKey;
import java.security.interfaces.RSAPrivateKey;
import java.security.spec.MGF1ParameterSpec;
import java.security.spec.PKCS8EncodedKeySpec;
import java.util.Arrays;
import java.util.Base64;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.crypto.AEADBadTagException;
import javax.crypto.Cipher;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.OAEPParameterSpec;
import javax.crypto.spec.PSource;
import javax.crypto.spec.SecretKeySpec;

/**
 * Helper service for decrypting JWE compact serialization payloads generated by
 * {@link JWEEncrypt}.
 *
 * <p>Example usage:</p>
 *
 * <pre>{@code
 * JWEDecrypt decryptor = new JWEDecrypt(
 *     "eyJhbGciOiJSU0EtT0FFUC0yNTYiLCJlbmMiOiJBMjU2R0NNIn0...",
 *     "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----"
 * );
 * String payloadJson = decryptor.decrypt();
 * }</pre>
 *
 * <p>The class does not perform console I/O. Command-line parsing and output are
 * owned by {@code com.sib.cvv.Main}.</p>
 */
public class JWEDecrypt {
    private static final Pattern JSON_STRING_FIELD = Pattern.compile("\"%s\"\\s*:\\s*\"((?:\\\\.|[^\"\\\\])*)\"");
    private static final int COMPACT_JWE_SEGMENTS = 5;
    private static final int CEK_BYTES = 32;
    private static final int IV_BYTES = 12;
    private static final int GCM_TAG_BITS = 128;
    private static final int GCM_TAG_BYTES = 16;

    private final String jweToken;
    private final String privateKeyPem;

    /**
     * Creates a JWE decryptor.
     *
     * @param jweToken compact JWE token with five base64url segments
     * @param privateKeyPem PKCS#8 RSA private key PEM text
     */
    public JWEDecrypt(String jweToken, String privateKeyPem) {
        this.jweToken = requireText(jweToken, "jweToken");
        this.privateKeyPem = requireText(privateKeyPem, "privateKey");
    }

    /**
     * Decrypts the configured JWE token and returns the plaintext JSON payload.
     *
     * @return decrypted minified JSON payload
     * @throws GeneralSecurityException when validation or decryption fails
     */
    public String decrypt() throws GeneralSecurityException {
        ParsedJwe parsedJwe = parseJwe(jweToken);
        validateHeader(parsedJwe.headerJson());

        byte[] cek = null;
        byte[] encryptedContent = null;
        byte[] plaintext = null;

        try {
            cek = decryptContentEncryptionKey(parsedJwe.encryptedKey(), parsePrivateKey(privateKeyPem));
            encryptedContent = combineCiphertextAndTag(parsedJwe.ciphertext(), parsedJwe.tag());
            plaintext = decryptContent(cek, parsedJwe.iv(), encryptedContent);
            String payloadJson = new String(plaintext, StandardCharsets.UTF_8);
            validateJsonObjectPayload(payloadJson);
            return payloadJson;
        } finally {
            clear(cek);
            clear(encryptedContent);
            clear(plaintext);
            parsedJwe.clear();
        }
    }

    private static ParsedJwe parseJwe(String token) throws GeneralSecurityException {
        String[] segments = token.split("\\.", -1);
        if (segments.length != COMPACT_JWE_SEGMENTS) {
            throw new GeneralSecurityException("Invalid JWE compact serialization format");
        }

        for (String segment : segments) {
            if (segment.isBlank() || !segment.matches("[A-Za-z0-9_-]+")) {
                throw new GeneralSecurityException("Invalid JWE compact serialization format");
            }
        }

        byte[] headerBytes;
        byte[] encryptedKey;
        byte[] iv;
        byte[] ciphertext;
        byte[] tag;

        try {
            headerBytes = KeyGeneratorUtil.base64urlDecode(segments[0]);
            encryptedKey = KeyGeneratorUtil.base64urlDecode(segments[1]);
            iv = KeyGeneratorUtil.base64urlDecode(segments[2]);
            ciphertext = KeyGeneratorUtil.base64urlDecode(segments[3]);
            tag = KeyGeneratorUtil.base64urlDecode(segments[4]);
        } catch (IllegalArgumentException exception) {
            throw new GeneralSecurityException("Invalid JWE compact serialization format", exception);
        }

        if (iv.length != IV_BYTES) {
            throw new GeneralSecurityException("Invalid JWE IV length");
        }

        if (tag.length != GCM_TAG_BYTES) {
            throw new GeneralSecurityException("Invalid JWE authentication tag length");
        }

        return new ParsedJwe(
                new String(headerBytes, StandardCharsets.UTF_8),
                encryptedKey,
                iv,
                ciphertext,
                tag);
    }

    private static void validateHeader(String headerJson) throws GeneralSecurityException {
        String algorithm = jsonStringField(headerJson, "alg");
        if (!"RSA-OAEP-256".equals(algorithm)) {
            throw new GeneralSecurityException("Unsupported algorithm: " + algorithm + ". Expected: RSA-OAEP-256");
        }

        String encryption = jsonStringField(headerJson, "enc");
        if (!"A256GCM".equals(encryption)) {
            throw new GeneralSecurityException("Unsupported encryption: " + encryption + ". Expected: A256GCM");
        }

        if (jsonStringField(headerJson, "zip") != null) {
            throw new GeneralSecurityException("Unsupported compression header: zip");
        }
    }

    private static byte[] decryptContentEncryptionKey(byte[] encryptedKey, PrivateKey privateKey)
            throws GeneralSecurityException {
        Cipher cipher = Cipher.getInstance("RSA/ECB/OAEPWithSHA-256AndMGF1Padding");
        OAEPParameterSpec oaepParameterSpec = new OAEPParameterSpec(
                "SHA-256",
                "MGF1",
                MGF1ParameterSpec.SHA256,
                PSource.PSpecified.DEFAULT);
        cipher.init(Cipher.DECRYPT_MODE, privateKey, oaepParameterSpec);
        byte[] cek;
        try {
            cek = cipher.doFinal(encryptedKey);
        } catch (GeneralSecurityException exception) {
            throw new GeneralSecurityException(
                    "Failed to decrypt CEK - invalid private key or corrupted token", exception);
        }

        if (cek.length != CEK_BYTES) {
            clear(cek);
            throw new GeneralSecurityException("Failed to decrypt CEK - invalid private key or corrupted token");
        }

        return cek;
    }

    private static byte[] decryptContent(byte[] cek, byte[] iv, byte[] encryptedContent)
            throws GeneralSecurityException {
        try {
            Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
            cipher.init(Cipher.DECRYPT_MODE, new SecretKeySpec(cek, "AES"), new GCMParameterSpec(GCM_TAG_BITS, iv));
            cipher.updateAAD(new byte[0]);
            return cipher.doFinal(encryptedContent);
        } catch (AEADBadTagException exception) {
            throw new GeneralSecurityException(
                    "Authentication tag verification failed - token may be tampered", exception);
        }
    }

    private static PrivateKey parsePrivateKey(String pem) throws GeneralSecurityException {
        String normalizedPem = pem.replace("\\n", "\n").trim();

        if (!normalizedPem.startsWith("-----BEGIN PRIVATE KEY-----")
                || !normalizedPem.endsWith("-----END PRIVATE KEY-----")) {
            throw new GeneralSecurityException("Invalid private key PEM format");
        }

        byte[] encoded = null;
        try {
            String base64 = normalizedPem
                    .replace("-----BEGIN PRIVATE KEY-----", "")
                    .replace("-----END PRIVATE KEY-----", "")
                    .replaceAll("\\s", "");
            encoded = Base64.getDecoder().decode(base64);
            PrivateKey privateKey = KeyFactory.getInstance("RSA").generatePrivate(new PKCS8EncodedKeySpec(encoded));

            if (privateKey instanceof RSAPrivateKey rsaPrivateKey
                    && rsaPrivateKey.getModulus().bitLength() < KeyGeneratorUtil.MIN_RSA_KEY_SIZE_BITS) {
                throw new GeneralSecurityException("RSA private key must be at least 2048 bits");
            }

            return privateKey;
        } catch (IllegalArgumentException exception) {
            throw new GeneralSecurityException("Invalid private key PEM format", exception);
        } finally {
            clear(encoded);
        }
    }

    private static byte[] combineCiphertextAndTag(byte[] ciphertext, byte[] tag) {
        byte[] encryptedContent = new byte[ciphertext.length + tag.length];
        System.arraycopy(ciphertext, 0, encryptedContent, 0, ciphertext.length);
        System.arraycopy(tag, 0, encryptedContent, ciphertext.length, tag.length);
        return encryptedContent;
    }

    private static String jsonStringField(String json, String fieldName) {
        Matcher matcher = Pattern.compile(String.format(JSON_STRING_FIELD.pattern(), fieldName)).matcher(json);
        if (!matcher.find()) {
            return null;
        }
        return unescapeJsonString(matcher.group(1));
    }

    private static String unescapeJsonString(String value) {
        String quoted = "\"" + value + "\"";
        StringBuilder result = new StringBuilder();

        for (int index = 1; index < quoted.length() - 1; index++) {
            char character = quoted.charAt(index);
            if (character != '\\') {
                result.append(character);
                continue;
            }

            char escaped = quoted.charAt(++index);
            switch (escaped) {
                case '"', '\\', '/' -> result.append(escaped);
                case 'b' -> result.append('\b');
                case 'f' -> result.append('\f');
                case 'n' -> result.append('\n');
                case 'r' -> result.append('\r');
                case 't' -> result.append('\t');
                case 'u' -> {
                    String hex = quoted.substring(index + 1, index + 5);
                    result.append((char) Integer.parseInt(hex, 16));
                    index += 4;
                }
                default -> result.append(escaped);
            }
        }

        return result.toString();
    }

    private static void validateJsonObjectPayload(String payloadJson) throws GeneralSecurityException {
        String trimmed = payloadJson.trim();
        if (!trimmed.startsWith("{") || !trimmed.endsWith("}")) {
            throw new GeneralSecurityException("Decrypted payload is not valid JSON");
        }

        if (jsonStringField(trimmed, "cardRef") == null) {
            throw new GeneralSecurityException("Decrypted payload is not valid JSON");
        }
    }

    private static String requireText(String value, String fieldName) {
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException("Missing required field: " + fieldName);
        }
        return value;
    }

    private static void clear(byte[] bytes) {
        if (bytes != null) {
            Arrays.fill(bytes, (byte) 0);
        }
    }

    private record ParsedJwe(String headerJson, byte[] encryptedKey, byte[] iv, byte[] ciphertext, byte[] tag) {
        private void clear() {
            JWEDecrypt.clear(encryptedKey);
            JWEDecrypt.clear(iv);
            JWEDecrypt.clear(ciphertext);
            JWEDecrypt.clear(tag);
        }
    }
}
